### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/magic-home#5]
### What's Required?

The codebase is currently littered with `os.Exit(1)`. In most of these occurrences, the code could be improved by returning an error. 

For example, https://github.com/apoclyps/magic-home/blob/bd6e945ae392f9cb2caa4c7a97085cdd6629cf33/cmd/power.go#L34 could return an InvalidPowerState error removing the logging and `os.Exit(1)` from the `pkg` and instead letting the power `cmd` handle the error.

**Comment by caioeverest** [comment]
Hi @apoclyps!

I open a PR adding a few improvements on the error handling: https://github.com/apoclyps/magic-home/pull/7
