### ISSUE TITLE
Improve Github Actions Workflow

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/magic-home#8]
### What's Required?

The current `test_and_build` workflow run's on every pull request. 

This should be split into a test workflow and a build workflow so releases are only produced on a merge to master.

See: https://github.com/apoclyps/magic-home/blob/master/.github/workflows/test_and_build.yml

### Acceptance Criteria

* build and test should be 2 separate workflows
* build should only run on a merge to master
* test should run on every pull request

**Comment by rafaelrubbioli** [comment]
Hi! I`m still learning to use the workflows, but i attempted solving this. Thanks!

**Comment by apoclyps** [comment]
Hi @rafaelrubbioli :wave: 

Thank you for the pull request; I had a quick look at the content's of the pull request and it looks good so far :+1:

**Comment by apoclyps** [comment]
You may also be interested in https://github.com/apoclyps/magic-home/issues/9 - It incorporates a few more action's from the market place.
