### ISSUE TITLE
Improve Release Process

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/magic-home#9]
### What's Required?

The current GitHub action provides a release for windows, mac, and linux however using https://github.com/goreleaser/goreleaser-action#usage would provide improved support for releasing other architectures/distributions.

The following blog post provides information on how this might be done: https://dev.to/koddr/github-action-for-release-your-go-projects-as-fast-and-easily-as-possible-20a2

**Acceptance Criteria** 
* Replace existing GitHub action releases with go-releaser
* Include support for additional architectures/distributions

**Comment by rafaelrubbioli** [comment]
I would like to try to help with this one!
